version: '3.8'

services:
  meu-rabbitmq:
    image: rabbitmq:3-management
    container_name: meu-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - app-network
    command: ["rabbitmq-server"]
    env_file:
      - .env
  
  criar-fila:
    image: rabbitmq:3-management
    container_name: criar-fila
    depends_on:
      - meu-rabbitmq
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
    entrypoint: >
      /bin/bash -c "  
      rabbitmqadmin --username=${RABBITMQ_USER} --password=${RABBITMQ_PASSWORD} declare queue name=${RABBITMQ_QUEUE} durable=true -H meu-rabbitmq
      "
    networks:
      - app-network
    env_file:
      - .env

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      -  ${DB_PATH}:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d/
    networks:
      - app-network
    env_file:
      - .env

  web:
    image: nginx:latest
    restart: always
    ports:
      - "${WEB_SERV_PORT}:80"
    volumes:
      - ${WEB_SERV_PATH}:/var/www/html/
      - ./config:/etc/nginx/conf.d
    env_file:
      - .env
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8083:8080" # Porta para acessar o Adminer
    networks:
      - app-network

  backend-intermediario:
    image: backend-intermediario  
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - rabbitmq_host=meu-rabbitmq
      - rabbitmq_queue=mensagens
    depends_on:
      - meu-rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
